library(usethis)
C0 <- as.matrix(read.csv("GPU_C0.csv"))
F <- as.matrix(read.csv("GPU_F.csv"))
G <- as.matrix(read.csv("GPU_G.csv"))
m0 <- as.matrix(read.csv("GPU_m0.csv"))
Y <- as.matrix(read.csv("GPU_Y.csv"))
usethis::use_data(C0, overwrite = TRUE, compress = 'xz')
usethis::use_data(F, overwrite = TRUE, compress = 'xz')
usethis::use_data(G, overwrite = TRUE, compress = 'xz')
usethis::use_data(m0, overwrite = TRUE, compress = 'xz')
usethis::use_data(Y, overwrite = TRUE, compress = 'xz')
