# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib CuMCMC
NULL

#' Run simulations
#'
#' @param N integer: Number of particles is solution.
#' @param d integer: Number of parameters.
#' @param timeSteps integer: Total time steps.
#' @param Y matrix: Input observations.
#' @param m0 vector: Initial parameters at t=0
#' @param C0 matrix: Initial covariant matrix at t=0
#' @param F matrix: covariant matrix for scaling particle samples 
#' @param sampler integer: Resampling sampler
#' @param distribution integer: Distribution for sampling particles 
run <- function(N, d, timeSteps, Y, m0, C0, F, sampler, distribution) {
    .Call('_CuMCMC_run', PACKAGE = 'CuMCMC', N, d, timeSteps, Y, m0, C0, F, sampler, distribution)
}

