# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib CuSMC
NULL

#' MultiVariateNormal Distribution
#'
#' @param  mu            [vector]: Mean vector.
#' @param  sigma         [matrix]: Covariant matrix.
#' @return draws         [vector]: Vector of real random draws from distribution
#' @export
#' @examples
#' mu = c(0, 0)
#' sigma = matrix(c(1, 0, 0, 1), nrow = 2)
#' CuSMC::MVN(mu, sigma)
MVN <- function(mu, sigma) {
    .Call('_CuSMC_MVN', PACKAGE = 'CuSMC', mu, sigma)
}

#' MultiVariateNormal Probability Density Function
#'
#' @param x             [vector]: x.
#' @param mu            [vector]: Mean vector.
#' @param sigma         [matrix]: Covariant matrix.
#' @return              [numeric]: Real value
#' @export
#' @examples
#' x = c(0, 0)
#' mu = c(0, 0)
#' sigma = matrix(c(1, 0, 0, 1), nrow = 2)
#' CuSMC::MVNPDF(x, mu, sigma)
MVNPDF <- function(x, mu, sigma) {
    .Call('_CuSMC_MVNPDF', PACKAGE = 'CuSMC', x, mu, sigma)
}

#' @useDynLib CuSMC
NULL

#' MultiVariate T Distribution
#'
#' @param  mu            [vector]: Location vector.
#' @param  sigma         [matrix]: Dispersion matrix.
#' @param nu             [float]: degrees of freedom.
#' @return draws         [vector]: Vector of random draws from distribution
#' @export
MVT <- function(mu, sigma, nu) {
    .Call('_CuSMC_MVT', PACKAGE = 'CuSMC', mu, sigma, nu)
}

#' MultiVariate T Probability Density Function
#'
#' @param x             [vector]: x.
#' @param mu            [vector]: Location vector.
#' @param sigma         [matrix]: Dispersion matrix.
#' @param nu            [float]: degrees of freedom.
#' @return              [numeric]: Real value
#' @export
MVTPDF <- function(x, mu, sigma, nu) {
    .Call('_CuSMC_MVTPDF', PACKAGE = 'CuSMC', x, mu, sigma, nu)
}

#' @useDynLib CuSMC
NULL

#' Run simulations
#'
#' @param N            [integer]: Number of particles is solution.
#' @param d            [integer]: Number of parameters.
#' @param timeSteps    [integer]: Total time steps.
#' @param Y            [matrix]: Input observations.
#' @param m0           [vector]: Initial parameters at t=0
#' @param C0           [matrix]: Initial covariant matrix at t=0
#' @param F            [matrix]: Covariant matrix for scaling particle samples
#' @param sampler      [string]: Resampling sampler
#' @param distribution [string]: Distribution for sampling particles
#' @export
run <- function(N, d, timeSteps, Y, m0, C0, F, G, V, W, df, resampler, distribution, p = 0L) {
    .Call('_CuSMC_run', PACKAGE = 'CuSMC', N, d, timeSteps, Y, m0, C0, F, G, V, W, df, resampler, distribution, p)
}

#' @useDynLib CuSMC
NULL

#' Metropolis Hastings Sampler
#'
#' @param  w           [vector]: Weights
#' @param  N           [matrix]: Number of weights
#' @param  B           [vector]: Bias term
#' @return a           [vector]: Ancestors
#' @export
#' @examples
#' w = c(0, 0)
#' N = 2
#' B = 10
#' CuSMC::metropolis_hastings(w, N, B)
metropolis_hastings <- function(w, N, B) {
    .Call('_CuSMC_metropolis_hastings', PACKAGE = 'CuSMC', w, N, B)
}

